name: "Node.js CI"

on:
  workflow_dispatch:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout action
        uses: actions/checkout@v2
      - name: setup node 20
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Install and run
        run: |
          npm ci --no-save
          npm start
